[package]
name = "http_req"
version = "0.4.0"
license = "MIT"
description = "simple HTTP client with built-in HTTPS support"
repository = "https://github.com/jayjamesjay/http_req"
authors = ["jajamesjay <kubaj55@poczta.fm>"]
readme = "README.md"
categories = ["web-programming::http-client", "network-programming"]
keywords = ["http", "client", "request"]
edition = "2018"

[dependencies]
native-tls = "^0.2.2"

[badges]
travis-ci = { repository = "jayjamesjay/http_req"}
