[package]
name = "wasmedge_http_req"
version = "0.8.1"
license = "MIT"
description = "simple and lightweight HTTP client with built-in HTTPS support"
repository = "https://github.com/L-jasmine/http_req"
authors = ["chensiheng"]
readme = "README.md"
categories = ["web-programming::http-client", "network-programming","wasmedge","wasi"]
keywords = ["http", "client", "request"]
edition = "2018"

[dependencies]
unicase = "^2.6"
wasmedge_wasi_socket = { git = "https://github.com/second-state/wasmedge_wasi_socket", branch = "main" }