[package]
name = "http_req"
version = "0.1.0"
license = "MIT"
description = "minimal library for making HTTP requests."
authors = ["jajamesjay <kubaj55@poczta.fm>"]

[dependencies]
native-tls = "0.2.1"
