[package]
name = "http_req"
version = "0.4.3"
license = "MIT"
description = "simple and lightweight HTTP client with built-in HTTPS support"
repository = "https://github.com/jayjamesjay/http_req"
authors = ["jajamesjay <kubaj55@poczta.fm>"]
readme = "README.md"
categories = ["web-programming::http-client", "network-programming"]
keywords = ["http", "client", "request"]
edition = "2018"

[features]
default = ["native-tls"]

[dependencies.native-tls]
version = "^0.2.2"
optional = true

[dependencies.rustls]
version = "0.15.0"
optional = true

[badges]
travis-ci = { repository = "jayjamesjay/http_req"}
