name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Build with Rusttls
      run: cargo build --verbose --features rusttls
    - name: Run tests
      run: cargo test --verbose
